name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: pnpm install

      - name: Build and zip
        run: |
          pnpm zip
          pnpm zip:firefox

      - name: Set job summary
        run: |
          echo $(ls -lhp dist/ | grep -v '/$' | awk '{print $5, $9}') >> $GITHUB_STEP_SUMMARY

      - name: Upload compiled Chrome extension
        uses: actions/upload-artifact@v4
        with:
          path: dist/chrome-mv3

      - name: Upload compiled Firefox extension
        uses: actions/upload-artifact@v4
        with:
          path: dist/firefox-mv2
